webapp/app/__init__.py
import os
from flask import Flask, render_template
from flask.ext.session import Session

# ---------------------------------------------------------------------------
# Define the WSGI application object.
# ---------------------------------------------------------------------------
app = Flask(__name__)
sess = Session()

# ---------------------------------------------------------------------------
# Configuration.
# ---------------------------------------------------------------------------
if os.environ.get('AWS_ENV') == 'prod':
    app.config.from_object('config.AWSProductionConfig')
else:
    app.config.from_object('config.DevelopmentConfig')

sess.init_app(app)

# ---------------------------------------------------------------------------
# Enable logging in production.
# ---------------------------------------------------------------------------
if os.environ.get('AWS_ENV') == 'prod':
    import logging
    from logging.handlers import RotatingFileHandler

    file_handler = RotatingFileHandler('jhh3.log', maxBytes=1024 * 1024 * 100, backupCount=20)
    file_handler.setLevel(logging.DEBUG)
    format_str = "%(asctime)s - %(levelname)s: (%(filename)s:%(lineno)s) %(message)s "
    file_formatter = logging.Formatter(format_str)
    file_handler.setFormatter(file_formatter)

    app.logger.addHandler(file_handler)

# ---------------------------------------------------------------------------
# Import the modules using the blueprint handler variables and register
# blueprints.
# ---------------------------------------------------------------------------
from app.main_module.controllers import mod as main_mod

app.register_blueprint(main_mod)

# ---------------------------------------------------------------------------
# HTTP error handling
# ---------------------------------------------------------------------------


@app.errorhandler(404)
def not_found(error):
    app.logger.warning(error)
    return render_template('error_module/404.html'), 404


@app.errorhandler(500)
def internal_error(error):
    app.logger.exception(error)
    return render_template('error_module/500.html'), 500

webapp/app/main_module/controllers.py
from flask import render_template, Blueprint, jsonify, request, session
from mind_reading_machine.mind_reader import MindReader
from seer.seer import SEER
from experts.experts import ExpertsCombo

# ---------------------------------------------------------------------------
# Define Blueprint.
# ---------------------------------------------------------------------------
mod = Blueprint('main', __name__, template_folder='../templates/main_module')

# ---------------------------------------------------------------------------
# Page views.
# ---------------------------------------------------------------------------


def reset_bot():
    bot = session.get('bot', 'Shannon')
    if bot == 'Shannon':
        session['penny_bot'] = MindReader()
    elif bot == 'Hagelbarger':
        session['penny_bot'] = SEER()
    elif bot == 'Expert':
        session['penny_bot'] = ExpertsCombo([MindReader(), SEER()])


# ---------------------------------------------------------------------------
# Page views.
# ---------------------------------------------------------------------------


@mod.route('/')
def index():
    return render_template("main_module/index.html")


@mod.route('/play')
def play_game():
    return render_template("main_module/play.html")


@mod.route('/game-over', methods=['POST'])
def game_over():
    reset_bot()
    return "", 200


@mod.route('/change-bot', methods=['POST'])
def change_bot():
    session['bot'] = request.form.get('bot', 'Shannon')
    reset_bot()
    return "", 200


@mod.route('/take-turn', methods=['GET'])
def take_turn():
    # Map right arrow key (39) to a 1
    action = int('39' == request.args.get('action'))
    # Get bot
    bot = session.get('penny_bot', False)
    if not bot:
        bot = session['penny_bot'] = MindReader()
    prev_computer_score = bot.computer_score
    bot.take_turn(action)
    result = {'computer_score': bot.computer_score,
              'player_score': bot.player_score,
              'won': prev_computer_score < bot.computer_score}
    return jsonify(**result)

webapp/app/templates/main_module/index.html
<html lang="en">
	<head>
    <meta charset="utf-8">
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <title>6.883 Final Project</title>
	</head>
	<body>
		<div id="layout">
			<div id="main">
				<div class="header">
					<h1>MIT 6.883 Final Project</h1>
					<h2>Matching Pennies with Experts</h2>
				</div>

				<div class="content">
					<h2 class="content-subhead">About</h2>
						<div id="play-button-div">
							<p>Click below to play now.</p>
							<a id="play-button" class="pure-button" href="{{ url_for('main.play_game') }}">Play!</a>
						</div>

					<h2 class="content-subhead">History</h2>
					<p>
						TODO
					</p>

					<h2 class="content-subhead">Contact Us</h2>
					<p>
						TODO
					</p>
				</div>
			</div>
		</div>
	</body>
</html>

webapp/app/templates/main_module/play.html
<html lang="en">
	<head>
    <meta charset="utf-8">
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
		<script src="{{ url_for('static', filename='js/matching_pennies.js') }}"></script>
    <title>6.883 Final Project</title>
	</head>
	<body>
		<div id="layout">
			<div id="main">
				<div class="header">
					<h1>MIT 6.883 Final Project</h1>
					<h2>Matching Pennies with Experts</h2>
				</div>

				<div class="content">
					<h2 class="content-subhead">Instructions</h2>
					<p>Press the left arrow key (&#9664;) or the right arrow key
					(&#9654;). If the computer (red) guesses your move, it moves
					forward. If not, you (green) move forward. First one to the finish
					wins! Can the computer read your mind?</p>
					<p>Press R to restart.</p>

					<h2 class="content-subhead">Game</h2>
					<div class="score-board">
						<div class="player">
							<h4>Computer</h4>
							<div class="score-box">
								<div id="cscore">0</div>
							</div>
						</div>
						<div class="player">
							<h4>You</h4>
							<div class="score-box">
								<div id="pscore">0</div>
							</div>
						</div>
					</div>
					<div id="matching-pennies" style="position:relative;">
						<img style="position:absolute;left:575px;height:100;" id="finish" src="{{ url_for('static', filename='images/finish.png') }}">
						<img style="position:absolute;width:575px;height:100;" id="finish" src="{{ url_for('static', filename='images/road.png') }}">
						<img style="position:absolute;height:34px;width:75;top:12" id="red-car" src="{{ url_for('static', filename='images/red-car.gif') }}">
						<img style="position:absolute;top:56px;height:34;width:75;" id="green-car" src="{{ url_for('static', filename='images/green-car.gif') }}">
					</div>
					<p>Pick a bot (changing bots restarts the game):</p>
					<form id="radio-bot" class="pure-form pure-g">
						<label for="option-one" class="pure-radio pure-u-1-3">
							<input id="option-one" type="radio" name="bot-choice" value="Shannon" checked>
							Shannon
						</label>
						<label for="option-two" class="pure-radio pure-u-1-3">
							<input id="option-two" type="radio" name="bot-choice" value="Hagelbarger">
							Hagelbarger
						</label>
						<label for="option-three" class="pure-radio pure-u-1-3">
							<input id="option-three" type="radio" name="bot-choice" value="Expert">
							Expert
						</label>
					</form>

					<h2 class="content-subhead">History</h2>
					<div id="history">
						<table id="history-table" class="pure-table pure-table-horizontal">
							<thead>
								<tr>
									<th>#</th>
									<th>Opponent</th>
									<th>Your Score</th>
									<th>Computer Score</th>
									<th>Outcome</th>
								</tr>
							</thead>

							<tbody></tbody>
						</table>
					</div>

				</div>
			</div>
		</div>
	</body>
</html>